name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Welcome message
            run: echo "My first Github Actions Job"
          - name: Welcome message
            run: git clone https://github.com/zafarjkhan/actions-1.git

