name: Generate ASCII Artwork

on: 
  push:
  workflow_dispatch:

jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest,ubuntu-20.04,windows-latest]
                images: [hello-world, alphine]
        runs-on: ${{ matrix.os}}
        steps:
            - name: Echo docker details
              run: docker info

            - name: Run image on ${{ matrix.os }}
              run: docker run ${{ matrix.images}}

